if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_vof_mass_conservation[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_vof_mass_conservation[1]_tests.cmake")
else()
  add_test(test_vof_mass_conservation_NOT_BUILT test_vof_mass_conservation_NOT_BUILT)
endif()
