if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_no_slip_boundary[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_no_slip_boundary[1]_tests.cmake")
else()
  add_test(test_no_slip_boundary_NOT_BUILT test_no_slip_boundary_NOT_BUILT)
endif()
