if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_bgk[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_bgk[1]_tests.cmake")
else()
  add_test(test_bgk_NOT_BUILT test_bgk_NOT_BUILT)
endif()
