if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_vof_evaporation_mass_loss[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_vof_evaporation_mass_loss[1]_tests.cmake")
else()
  add_test(test_vof_evaporation_mass_loss_NOT_BUILT test_vof_evaporation_mass_loss_NOT_BUILT)
endif()
