if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_thermal_lbm[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_thermal_lbm[1]_tests.cmake")
else()
  add_test(test_thermal_lbm_NOT_BUILT test_thermal_lbm_NOT_BUILT)
endif()
