if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_gravity_driven_flow[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_gravity_driven_flow[1]_tests.cmake")
else()
  add_test(test_gravity_driven_flow_NOT_BUILT test_gravity_driven_flow_NOT_BUILT)
endif()
