if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_temperature_bounds[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_temperature_bounds[1]_tests.cmake")
else()
  add_test(test_temperature_bounds_NOT_BUILT test_temperature_bounds_NOT_BUILT)
endif()
