if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_multiphysics_step2[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_multiphysics_step2[1]_tests.cmake")
else()
  add_test(test_multiphysics_step2_NOT_BUILT test_multiphysics_step2_NOT_BUILT)
endif()
