if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_omega_reduction[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_omega_reduction[1]_tests.cmake")
else()
  add_test(test_omega_reduction_NOT_BUILT test_omega_reduction_NOT_BUILT)
endif()
