if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_vof_cell_conversion[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_vof_cell_conversion[1]_tests.cmake")
else()
  add_test(test_vof_cell_conversion_NOT_BUILT test_vof_cell_conversion_NOT_BUILT)
endif()
