if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_vtk_liquid_fraction[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_vtk_liquid_fraction[1]_tests.cmake")
else()
  add_test(test_vtk_liquid_fraction_NOT_BUILT test_vtk_liquid_fraction_NOT_BUILT)
endif()
