if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_fluid_boundaries[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_fluid_boundaries[1]_tests.cmake")
else()
  add_test(test_fluid_boundaries_NOT_BUILT test_fluid_boundaries_NOT_BUILT)
endif()
