if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_marangoni_system[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_marangoni_system[1]_tests.cmake")
else()
  add_test(test_marangoni_system_NOT_BUILT test_marangoni_system_NOT_BUILT)
endif()
