if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_evaporation_temperature_check[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_evaporation_temperature_check[1]_tests.cmake")
else()
  add_test(test_evaporation_temperature_check_NOT_BUILT test_evaporation_temperature_check_NOT_BUILT)
endif()
