if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_flux_limiter_overhead[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_flux_limiter_overhead[1]_tests.cmake")
else()
  add_test(test_flux_limiter_overhead_NOT_BUILT test_flux_limiter_overhead_NOT_BUILT)
endif()
