if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_dirichlet_bc[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_dirichlet_bc[1]_tests.cmake")
else()
  add_test(test_dirichlet_bc_NOT_BUILT test_dirichlet_bc_NOT_BUILT)
endif()
