if(EXISTS "/home/yzk/LBMProject/build_check/tests/test_boundary[1]_tests.cmake")
  include("/home/yzk/LBMProject/build_check/tests/test_boundary[1]_tests.cmake")
else()
  add_test(test_boundary_NOT_BUILT test_boundary_NOT_BUILT)
endif()
