"""Generate test STL files for STL pipeline validation.

Outputs:
  test_sphere_r05.stl       — sphere radius 0.5 m centered at origin (icosphere, 80 tris)
  test_cube_l1.stl          — unit cube [0,1]^3 (12 tris)
"""
import struct
import os
import numpy as np

ROOT = "/home/yzk/CompressibleCFD"
os.makedirs(f"{ROOT}/test_data", exist_ok=True)


def icosphere(subdivs=1):
    """Icosphere with iterated 1→4 face split, vertices projected to unit sphere."""
    t = (1.0 + 5.0 ** 0.5) / 2.0
    verts = [
        np.array(v, dtype=float)
        for v in [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
                  (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
                  (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    ]
    verts = [v / np.linalg.norm(v) for v in verts]
    faces = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
             (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
             (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
             (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
    for _ in range(subdivs):
        cache = {}
        def mid(a, b):
            key = (min(a, b), max(a, b))
            if key in cache: return cache[key]
            m = (verts[a] + verts[b]) / 2.0
            m /= np.linalg.norm(m)
            verts.append(m)
            idx = len(verts) - 1
            cache[key] = idx
            return idx
        new_faces = []
        for a, b, c in faces:
            ab = mid(a, b); bc = mid(b, c); ca = mid(c, a)
            new_faces += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = new_faces
    return [(verts[a], verts[b], verts[c]) for a, b, c in faces]


def cube_tris(L=1.0):
    v = np.array([
        [0,0,0],[L,0,0],[L,L,0],[0,L,0],
        [0,0,L],[L,0,L],[L,L,L],[0,L,L],
    ], dtype=float)
    # 12 triangles, CCW outward
    F = [
        (0,2,1),(0,3,2),  # bottom -z
        (4,5,6),(4,6,7),  # top +z
        (0,1,5),(0,5,4),  # front -y
        (3,7,6),(3,6,2),  # back +y
        (0,4,7),(0,7,3),  # left -x
        (1,2,6),(1,6,5),  # right +x
    ]
    return [(v[a], v[b], v[c]) for (a,b,c) in F]


def write_binary_stl(path, tris):
    with open(path, "wb") as f:
        header = b"binary STL generated by make_test_stl.py" + b" " * 80
        f.write(header[:80])
        f.write(struct.pack("<I", len(tris)))
        for v0, v1, v2 in tris:
            n = np.cross(v1 - v0, v2 - v0)
            n /= max(np.linalg.norm(n), 1e-30)
            f.write(struct.pack("<fff", *n))
            f.write(struct.pack("<fff", *v0))
            f.write(struct.pack("<fff", *v1))
            f.write(struct.pack("<fff", *v2))
            f.write(struct.pack("<H", 0))


def write_ascii_stl(path, tris):
    with open(path, "w") as f:
        f.write("solid testmesh\n")
        for v0, v1, v2 in tris:
            n = np.cross(v1 - v0, v2 - v0)
            n /= max(np.linalg.norm(n), 1e-30)
            f.write(f" facet normal {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
            f.write("  outer loop\n")
            for v in (v0, v1, v2):
                f.write(f"   vertex {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
            f.write("  endloop\n")
            f.write(" endfacet\n")
        f.write("endsolid testmesh\n")


# Sphere radius 0.5
ico = icosphere(subdivs=1)
sphere = [(0.5 * v0, 0.5 * v1, 0.5 * v2) for v0, v1, v2 in ico]
write_binary_stl(f"{ROOT}/test_data/test_sphere_r05.stl", sphere)
print(f"sphere: {len(sphere)} tris → {ROOT}/test_data/test_sphere_r05.stl")

cube = cube_tris(L=1.0)
write_ascii_stl(f"{ROOT}/test_data/test_cube_l1.stl", cube)
print(f"cube: {len(cube)} tris → {ROOT}/test_data/test_cube_l1.stl")
