# CMake generated Testfile for 
# Source directory: /home/yzk/LBMProject/tests/validation
# Build directory: /home/yzk/LBMProject/build_check/tests/validation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MarangoniVelocityValidation "/home/yzk/LBMProject/build_check/tests/validation/test_marangoni_velocity")
set_tests_properties(MarangoniVelocityValidation PROPERTIES  LABELS "validation;marangoni;velocity;critical" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;43;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(RealisticLPBFInitialConditions "/home/yzk/LBMProject/build_check/tests/validation/test_realistic_lpbf_initial_conditions")
set_tests_properties(RealisticLPBFInitialConditions PROPERTIES  LABELS "validation;lpbf;initial_conditions;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;80;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(DivergenceFreeVelocity "/home/yzk/LBMProject/build_check/tests/validation/test_divergence_free")
set_tests_properties(DivergenceFreeVelocity PROPERTIES  LABELS "validation;divergence;incompressibility;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;115;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(PhaseChangeRobustness "/home/yzk/LBMProject/build_check/tests/validation/test_phase_change_robustness")
set_tests_properties(PhaseChangeRobustness PROPERTIES  LABELS "validation;phase_change;robustness;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;152;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(LaserShutoffConfigurable "/home/yzk/LBMProject/build_check/tests/validation/test_laser_shutoff_configurable")
set_tests_properties(LaserShutoffConfigurable PROPERTIES  LABELS "validation;laser;shutoff;stability;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;189;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(EvaporationHertzKnudsenFormula "/home/yzk/LBMProject/build_check/tests/validation/test_evaporation_hertz_knudsen")
set_tests_properties(EvaporationHertzKnudsenFormula PROPERTIES  LABELS "validation;evaporation;hertz_knudsen;week1;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;226;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(SubstrateCoolingBoundaryCondition "/home/yzk/LBMProject/build_check/tests/validation/test_substrate_cooling_bc")
set_tests_properties(SubstrateCoolingBoundaryCondition PROPERTIES  LABELS "validation;substrate;cooling;bc;week1;critical" TIMEOUT "180" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;259;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(PureConductionBenchmark "/home/yzk/LBMProject/build_check/tests/validation/test_pure_conduction")
set_tests_properties(PureConductionBenchmark PROPERTIES  LABELS "validation;benchmark;conduction;analytical;week2;critical" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;296;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(StefanProblemBenchmark "/home/yzk/LBMProject/build_check/tests/validation/test_stefan_problem")
set_tests_properties(StefanProblemBenchmark PROPERTIES  LABELS "validation;benchmark;stefan;phase_change;analytical;week2;critical" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;329;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(EvaporationRateBenchmark "/home/yzk/LBMProject/build_check/tests/validation/test_evaporation_rate")
set_tests_properties(EvaporationRateBenchmark PROPERTIES  LABELS "validation;benchmark;evaporation;hertz_knudsen;analytical;week2;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;360;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(GridIndependenceValidation "/home/yzk/LBMProject/build_check/tests/validation/test_grid_convergence")
set_tests_properties(GridIndependenceValidation PROPERTIES  LABELS "validation;convergence;grid;analytical;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;395;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(TimestepConvergenceValidation "/home/yzk/LBMProject/build_check/tests/validation/test_timestep_convergence")
set_tests_properties(TimestepConvergenceValidation PROPERTIES  LABELS "validation;convergence;timestep;analytical;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;429;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(EnergyConservationTimestepValidation "/home/yzk/LBMProject/build_check/tests/validation/test_energy_conservation_timestep")
set_tests_properties(EnergyConservationTimestepValidation PROPERTIES  LABELS "validation;energy;conservation;week2;critical" TIMEOUT "1800" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;458;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(RegressionTest50W "/home/yzk/LBMProject/build_check/tests/validation/test_regression_50W")
set_tests_properties(RegressionTest50W PROPERTIES  LABELS "validation;regression;baseline;week2;critical" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;486;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(CFLStabilityCheck "/home/yzk/LBMProject/build_check/tests/validation/test_cfl_stability")
set_tests_properties(CFLStabilityCheck PROPERTIES  LABELS "validation;stability;cfl;week2;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;514;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(ConfigurationParserValidation "/home/yzk/LBMProject/build_check/tests/validation/test_config_parser")
set_tests_properties(ConfigurationParserValidation PROPERTIES  LABELS "validation;config;parser;week2;critical" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;542;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(Case1_3D_HeatDiffusion_Senior "/home/yzk/LBMProject/build_check/tests/validation/test_3d_heat_diffusion_senior")
set_tests_properties(Case1_3D_HeatDiffusion_Senior PROPERTIES  LABELS "validation;senior;thermal;3d;gaussian;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;580;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(Case1_3D_HeatDiffusion_Fixed "/home/yzk/LBMProject/build_check/tests/validation/test_3d_heat_diffusion_fixed")
set_tests_properties(Case1_3D_HeatDiffusion_Fixed PROPERTIES  LABELS "validation;senior;thermal;3d;gaussian;fixed;staircase" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;615;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(Case5_LaserMelting_Senior "/home/yzk/LBMProject/build_check/tests/validation/test_laser_melting_senior")
set_tests_properties(Case5_LaserMelting_Senior PROPERTIES  LABELS "validation;senior;laser;melting;multiphysics;critical" TIMEOUT "1800" WORKING_DIRECTORY "/home/yzk/LBMProject" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;653;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(LaserMeltingIron "/home/yzk/LBMProject/build_check/tests/validation/test_laser_melting_iron")
set_tests_properties(LaserMeltingIron PROPERTIES  LABELS "validation;laser_melting;phase_2;steel;openfoam_reference" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;691;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(EnergyBudgetConservation "/home/yzk/LBMProject/build_check/tests/validation/test_energy_budget")
set_tests_properties(EnergyBudgetConservation PROPERTIES  LABELS "validation;energy;conservation;budget;critical" TIMEOUT "300" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;728;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(ThermalSourceEnergyConservation "/home/yzk/LBMProject/build_check/tests/validation/thermal_source_energy_test")
set_tests_properties(ThermalSourceEnergyConservation PROPERTIES  LABELS "validation;thermal;source;energy;unit;critical" TIMEOUT "60" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;763;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(ThermalWalberlaMatch "/home/yzk/LBMProject/build_check/tests/validation/test_thermal_walberla_match")
set_tests_properties(ThermalWalberlaMatch PROPERTIES  LABELS "validation;thermal;walberla;match;lbm;fd;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;800;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(FDThermalReference "/home/yzk/LBMProject/build_check/tests/validation/test_fd_thermal_reference")
set_tests_properties(FDThermalReference PROPERTIES  LABELS "validation;thermal;fd;reference;walberla" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;835;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(GaussianDiffusion "/home/yzk/LBMProject/build_check/tests/validation/test_gaussian_diffusion")
set_tests_properties(GaussianDiffusion PROPERTIES  LABELS "validation;thermal;analytical;gaussian;diffusion;critical" TIMEOUT "300" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;872;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(EnergyConservationValidation "/home/yzk/LBMProject/build_check/tests/validation/test_energy_conservation")
set_tests_properties(EnergyConservationValidation PROPERTIES  LABELS "validation;energy;conservation;laser;thermal;critical" TIMEOUT "300" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;909;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(LidDrivenCavityRe100 "/home/yzk/LBMProject/build_check/tests/validation/test_lid_driven_cavity_re100")
set_tests_properties(LidDrivenCavityRe100 PROPERTIES  LABELS "validation;fluid;benchmark;critical;phase1" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;948;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(LidDrivenCavityRe400 "/home/yzk/LBMProject/build_check/tests/validation/test_lid_driven_cavity_re400")
set_tests_properties(LidDrivenCavityRe400 PROPERTIES  LABELS "validation;fluid;benchmark;phase1" TIMEOUT "900" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;983;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(FluidGridConvergence "/home/yzk/LBMProject/build_check/tests/validation/test_fluid_grid_convergence")
set_tests_properties(FluidGridConvergence PROPERTIES  LABELS "validation;fluid;convergence;analytical;phase1" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1018;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(NaturalConvectionRa1e4 "/home/yzk/LBMProject/build_check/tests/validation/test_natural_convection" "--gtest_filter=NaturalConvectionTest.RayleighNumber1e4")
set_tests_properties(NaturalConvectionRa1e4 PROPERTIES  LABELS "validation;thermal;fluid;buoyancy;benchmark;critical;phase2" TIMEOUT "900" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1053;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(NaturalConvectionRa1e3 "/home/yzk/LBMProject/build_check/tests/validation/test_natural_convection" "--gtest_filter=NaturalConvectionTest.RayleighNumber1e3")
set_tests_properties(NaturalConvectionRa1e3 PROPERTIES  LABELS "validation;thermal;fluid;buoyancy;benchmark;phase2" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1063;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(CouettePoiseuille "/home/yzk/LBMProject/build_check/tests/validation/test_couette_poiseuille")
set_tests_properties(CouettePoiseuille PROPERTIES  LABELS "validation;fluid;benchmark;analytical;phase1;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1101;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(TRTCouettePoiseuilleFlow "/home/yzk/LBMProject/build_check/tests/validation/test_trt_couette_poiseuille")
set_tests_properties(TRTCouettePoiseuilleFlow PROPERTIES  LABELS "validation;fluid;couette_poiseuille;trt;analytical;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1137;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(OscillatingDropletValidation "/home/yzk/LBMProject/build_check/tests/validation/test_oscillating_droplet")
set_tests_properties(OscillatingDropletValidation PROPERTIES  LABELS "validation;vof;surface_tension;oscillating_droplet;critical" TIMEOUT "1800" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1176;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(VOFBuoyancyForce "/home/yzk/LBMProject/build_check/tests/validation/test_vof_buoyancy")
set_tests_properties(VOFBuoyancyForce PROPERTIES  LABELS "validation;force;buoyancy;vof;unit_test" TIMEOUT "10" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1207;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(M2_RisingBubble2D "/home/yzk/LBMProject/build_check/tests/validation/test_rising_bubble_2d")
set_tests_properties(M2_RisingBubble2D PROPERTIES  LABELS "validation;vof;buoyancy;rising_bubble;m2;critical" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1240;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(RayleighTaylorGerrisExact "/home/yzk/LBMProject/build_check/tests/validation/test_rayleigh_taylor_gerris_exact")
set_tests_properties(RayleighTaylorGerrisExact PROPERTIES  WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1273;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(RayleighTaylorValidation "/home/yzk/LBMProject/build_check/tests/validation/test_rayleigh_taylor_validation")
set_tests_properties(RayleighTaylorValidation PROPERTIES  LABELS "validation;vof;analytical;rayleigh_taylor;critical" TIMEOUT "1800" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1301;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(RTTRTValidation "/home/yzk/LBMProject/build_check/tests/validation/test_rt_trt_validation")
set_tests_properties(RTTRTValidation PROPERTIES  LABELS "validation;trt;rayleigh_taylor;re3000" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1334;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(PhaseInversion "/home/yzk/LBMProject/build_check/tests/validation/test_phase_inversion")
set_tests_properties(PhaseInversion PROPERTIES  LABELS "validation;vof;buoyancy;phase_inversion" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1367;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(VOFMassConservationTVD "/home/yzk/LBMProject/build_check/tests/validation/test_vof_mass_conservation_tvd")
set_tests_properties(VOFMassConservationTVD PROPERTIES  LABELS "validation;vof;mass_conservation;tvd;advection" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1400;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(MarangoniVelocityScale "/home/yzk/LBMProject/build_check/tests/validation/test_marangoni_velocity_scale")
set_tests_properties(MarangoniVelocityScale PROPERTIES  LABELS "validation;marangoni;velocity;scale" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1465;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(TaylorGreen2D "/home/yzk/LBMProject/build_check/tests/validation/test_taylor_green_2d")
set_tests_properties(TaylorGreen2D PROPERTIES  LABELS "validation;fluid;taylor_green" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1502;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(ThermalTimestepConvergence "/home/yzk/LBMProject/build_check/tests/validation/test_thermal_timestep_convergence")
set_tests_properties(ThermalTimestepConvergence PROPERTIES  LABELS "validation;thermal;timestep;convergence" TIMEOUT "600" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1539;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(NewtonBisectionFallback "/home/yzk/LBMProject/build_check/tests/validation/test_newton_bisection_fallback")
set_tests_properties(NewtonBisectionFallback PROPERTIES  LABELS "validation;phase_change;numerical" TIMEOUT "120" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1577;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(PowderBedGeneration "/home/yzk/LBMProject/build_check/tests/validation/test_powder_bed_generation")
set_tests_properties(PowderBedGeneration PROPERTIES  LABELS "validation;powder_bed;lpbf" TIMEOUT "120" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1611;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(KhairallahMeltPool "/home/yzk/LBMProject/build_check/tests/validation/test_khairallah_melt_pool")
set_tests_properties(KhairallahMeltPool PROPERTIES  LABELS "validation;laser_melting;melt_pool;khairallah" TIMEOUT "1800" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1646;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
add_test(TVDVOFAdvection "/home/yzk/LBMProject/build_check/tests/validation/test_tvd_vof_advection")
set_tests_properties(TVDVOFAdvection PROPERTIES  LABELS "validation;vof;tvd;advection" TIMEOUT "300" WORKING_DIRECTORY "/home/yzk/LBMProject/build_check" _BACKTRACE_TRIPLES "/home/yzk/LBMProject/tests/validation/CMakeLists.txt;1679;add_test;/home/yzk/LBMProject/tests/validation/CMakeLists.txt;0;")
subdirs("multiphysics")
