#!/usr/bin/env python3
"""
Melt Pool Depth Analysis Script

This script extracts and analyzes melt pool depth from VTK output files
generated by the laser melting validation test.

Usage:
    python3 analyze_melt_pool_depth.py <vtk_directory>

Output:
    - Melt pool depth vs time CSV file
    - Summary statistics
"""

import os
import sys
import numpy as np
import vtk
from vtk.util import numpy_support
import csv
from pathlib import Path


def read_vtk_structured_points(filename):
    """
    Read VTK structured points file

    Args:
        filename: Path to VTK file

    Returns:
        Dictionary containing grid info and field data
    """
    reader = vtk.vtkStructuredPointsReader()
    reader.SetFileName(filename)
    reader.Update()

    data = reader.GetOutput()
    dims = data.GetDimensions()
    spacing = data.GetSpacing()

    # Extract fields
    point_data = data.GetPointData()

    result = {
        'dims': dims,
        'spacing': spacing,
        'nx': dims[0],
        'ny': dims[1],
        'nz': dims[2],
        'dx': spacing[0],
        'dy': spacing[1],
        'dz': spacing[2]
    }

    # Extract scalar fields
    for i in range(point_data.GetNumberOfArrays()):
        array_name = point_data.GetArrayName(i)
        vtk_array = point_data.GetArray(i)
        numpy_array = numpy_support.vtk_to_numpy(vtk_array)
        result[array_name] = numpy_array

    return result


def compute_melt_pool_depth(vtk_data, T_liquidus=1923.0):
    """
    Compute melt pool depth from VTK data

    Depth = distance from interface (f=0.5) to deepest point with T > T_liquidus

    Args:
        vtk_data: Dictionary from read_vtk_structured_points
        T_liquidus: Liquidus temperature [K]

    Returns:
        Melt pool depth [m]
    """
    nx, ny, nz = vtk_data['nx'], vtk_data['ny'], vtk_data['nz']
    dx, dy, dz = vtk_data['dx'], vtk_data['dy'], vtk_data['dz']

    temperature = vtk_data['Temperature'].reshape((nz, ny, nx))
    fill_level = vtk_data['FillLevel'].reshape((nz, ny, nx))

    # Find interface z-position (average z where 0.3 < f < 0.7)
    interface_z = 0.0
    interface_count = 0

    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                f = fill_level[k, j, i]
                if 0.3 < f < 0.7:
                    interface_z += k
                    interface_count += 1

    if interface_count > 0:
        interface_z /= interface_count
    else:
        interface_z = nz - 1  # Default to top

    # Find deepest point with T > T_liquidus and f > 0.5
    max_depth = 0.0

    for k in range(int(interface_z)):
        for j in range(ny):
            for i in range(nx):
                T = temperature[k, j, i]
                f = fill_level[k, j, i]

                # Liquid cells with T > T_liquidus
                if f > 0.5 and T > T_liquidus:
                    depth = (interface_z - k) * dz
                    max_depth = max(max_depth, depth)

    return max_depth


def compute_max_surface_temperature(vtk_data):
    """
    Compute maximum temperature at the surface (interface cells)

    Args:
        vtk_data: Dictionary from read_vtk_structured_points

    Returns:
        Maximum surface temperature [K]
    """
    nx, ny, nz = vtk_data['nx'], vtk_data['ny'], vtk_data['nz']

    temperature = vtk_data['Temperature'].reshape((nz, ny, nx))
    fill_level = vtk_data['FillLevel'].reshape((nz, ny, nx))

    max_T = 0.0

    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                f = fill_level[k, j, i]
                # Interface cells
                if 0.3 < f < 0.7:
                    max_T = max(max_T, temperature[k, j, i])

    return max_T


def extract_timestep_from_filename(filename):
    """
    Extract timestep number from VTK filename

    Assumes format: laser_melting_XXXXXX.vtk

    Args:
        filename: VTK filename

    Returns:
        Timestep number (integer)
    """
    import re
    match = re.search(r'laser_melting_(\d+)\.vtk', filename)
    if match:
        return int(match.group(1))
    return 0


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_melt_pool_depth.py <vtk_directory>")
        print("Example: python3 analyze_melt_pool_depth.py output_laser_melting_senior")
        sys.exit(1)

    vtk_dir = sys.argv[1]

    if not os.path.isdir(vtk_dir):
        print(f"Error: Directory not found: {vtk_dir}")
        sys.exit(1)

    print(f"Analyzing VTK files in: {vtk_dir}")
    print("=" * 80)

    # Find all VTK files
    vtk_files = sorted([f for f in os.listdir(vtk_dir) if f.endswith('.vtk')])

    if not vtk_files:
        print(f"Error: No VTK files found in {vtk_dir}")
        sys.exit(1)

    print(f"Found {len(vtk_files)} VTK files")

    # Process each file
    results = []

    for vtk_file in vtk_files:
        filepath = os.path.join(vtk_dir, vtk_file)

        # Extract timestep
        timestep = extract_timestep_from_filename(vtk_file)

        # Read VTK data
        try:
            vtk_data = read_vtk_structured_points(filepath)
        except Exception as e:
            print(f"Warning: Failed to read {vtk_file}: {e}")
            continue

        # Compute metrics
        depth = compute_melt_pool_depth(vtk_data)
        max_T_surface = compute_max_surface_temperature(vtk_data)

        # Assume dt = 1 ns, output_interval = 1000
        dt = 1e-9  # s
        output_interval = 1000
        time = timestep * dt

        results.append({
            'timestep': timestep,
            'time_us': time * 1e6,
            'depth_um': depth * 1e6,
            'max_T_surface_K': max_T_surface
        })

        if len(results) % 10 == 0:
            print(f"Processed {len(results)} files...")

    print(f"Processed {len(results)} files total")
    print("=" * 80)

    # Write results to CSV
    output_csv = os.path.join(vtk_dir, 'melt_pool_depth_extracted.csv')

    with open(output_csv, 'w', newline='') as csvfile:
        fieldnames = ['timestep', 'time_us', 'depth_um', 'max_T_surface_K']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for row in results:
            writer.writerow(row)

    print(f"Results written to: {output_csv}")

    # Print summary statistics
    print("\n=== Summary Statistics ===")

    depths = [r['depth_um'] for r in results]
    times = [r['time_us'] for r in results]
    temps = [r['max_T_surface_K'] for r in results]

    max_depth = max(depths)
    max_depth_time = times[depths.index(max_depth)]

    print(f"Peak melt pool depth: {max_depth:.2f} μm at t = {max_depth_time:.2f} μs")
    print(f"Maximum surface temperature: {max(temps):.1f} K")
    print(f"Time range: {min(times):.2f} - {max(times):.2f} μs")

    # Depth at key times
    print("\nMelt pool depth at key times:")
    for target_time in [25, 50, 60, 75]:
        # Find closest time
        idx = min(range(len(times)), key=lambda i: abs(times[i] - target_time))
        print(f"  t = {target_time:5.1f} μs: {depths[idx]:7.2f} μm")

    print("\n" + "=" * 80)
    print("Analysis complete!")


if __name__ == '__main__':
    main()
