#!/usr/bin/env python3
"""
visualize_temperature.py
Post-processing and visualization script for LBM laser heating simulation

This script reads VTK files generated by the simulation and creates:
- Temperature field plots
- Animations
- Statistical analysis
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.colors import LinearSegmentedColormap
import glob
import re
import sys
import os
from pathlib import Path

def read_vtk_structured_points(filename):
    """
    Read VTK structured points file containing temperature data

    Args:
        filename: Path to VTK file

    Returns:
        temperature: 3D numpy array of temperature values
        dimensions: Tuple of (nx, ny, nz)
        spacing: Tuple of (dx, dy, dz)
    """
    with open(filename, 'r') as f:
        lines = f.readlines()

    dimensions = None
    spacing = None
    temperature = []
    laser_intensity = []

    # Parse header
    for i, line in enumerate(lines):
        if line.startswith('DIMENSIONS'):
            parts = line.split()
            dimensions = (int(parts[1]), int(parts[2]), int(parts[3]))
        elif line.startswith('SPACING'):
            parts = line.split()
            spacing = (float(parts[1]), float(parts[2]), float(parts[3]))
        elif 'SCALARS Temperature' in line:
            # Start reading temperature data
            data_start = i + 2  # Skip LOOKUP_TABLE line
            break

    # Read temperature data
    if dimensions:
        nx, ny, nz = dimensions
        n_points = nx * ny * nz

        for i in range(data_start, data_start + n_points):
            if i < len(lines):
                try:
                    temperature.append(float(lines[i].strip()))
                except:
                    break

        # Look for laser intensity data
        for i in range(data_start + n_points, len(lines)):
            if 'SCALARS LaserIntensity' in lines[i]:
                laser_start = i + 2
                for j in range(laser_start, min(laser_start + n_points, len(lines))):
                    try:
                        laser_intensity.append(float(lines[j].strip()))
                    except:
                        break
                break

    # Reshape to 3D array
    if temperature and dimensions:
        temp_array = np.array(temperature).reshape((nz, ny, nx))
        laser_array = np.array(laser_intensity).reshape((nz, ny, nx)) if laser_intensity else None
        return temp_array, dimensions, spacing, laser_array

    return None, None, None, None

def create_custom_colormap():
    """Create a custom colormap for temperature visualization"""
    colors = [
        (0.0, 0.0, 0.5),   # Dark blue
        (0.0, 0.5, 1.0),   # Light blue
        (0.0, 1.0, 1.0),   # Cyan
        (0.0, 1.0, 0.0),   # Green
        (1.0, 1.0, 0.0),   # Yellow
        (1.0, 0.5, 0.0),   # Orange
        (1.0, 0.0, 0.0),   # Red
        (1.0, 0.0, 1.0),   # Magenta
        (1.0, 1.0, 1.0),   # White
    ]
    n_bins = 256
    cmap = LinearSegmentedColormap.from_list('temperature', colors, N=n_bins)
    return cmap

def plot_single_timestep(vtk_file, z_slice=0, save_fig=False):
    """
    Plot temperature field from a single VTK file

    Args:
        vtk_file: Path to VTK file
        z_slice: Z-index for 2D slice (default: 0 = surface)
        save_fig: Whether to save figure as PNG
    """
    temp, dims, spacing, laser = read_vtk_structured_points(vtk_file)

    if temp is None:
        print(f"Error reading file: {vtk_file}")
        return

    nx, ny, nz = dims
    dx, dy, dz = spacing

    # Create figure with subplots
    fig = plt.figure(figsize=(15, 5))

    # 1. XY slice (top view)
    ax1 = fig.add_subplot(131)
    im1 = ax1.imshow(temp[z_slice, :, :],
                     extent=[0, nx*dx*1e6, 0, ny*dy*1e6],
                     origin='lower', cmap=create_custom_colormap(),
                     vmin=300, vmax=800)
    ax1.set_xlabel('X (µm)')
    ax1.set_ylabel('Y (µm)')
    ax1.set_title(f'Temperature at z={z_slice*dz*1e6:.1f} µm')
    plt.colorbar(im1, ax=ax1, label='Temperature (K)')

    # Add laser contour if available
    if laser is not None:
        laser_slice = laser[z_slice, :, :]
        contour = ax1.contour(np.linspace(0, nx*dx*1e6, nx),
                             np.linspace(0, ny*dy*1e6, ny),
                             laser_slice, levels=[0.1, 0.5, 0.9],
                             colors='white', linewidths=1, alpha=0.5)

    # 2. XZ slice (side view)
    ax2 = fig.add_subplot(132)
    im2 = ax2.imshow(temp[:, ny//2, :],
                     extent=[0, nx*dx*1e6, 0, nz*dz*1e6],
                     origin='lower', cmap=create_custom_colormap(),
                     vmin=300, vmax=800, aspect='auto')
    ax2.set_xlabel('X (µm)')
    ax2.set_ylabel('Z (µm)')
    ax2.set_title(f'Temperature at y={ny//2*dy*1e6:.1f} µm')
    plt.colorbar(im2, ax=ax2, label='Temperature (K)')

    # 3. Temperature histogram
    ax3 = fig.add_subplot(133)
    temp_flat = temp.flatten()
    ax3.hist(temp_flat, bins=50, color='blue', alpha=0.7, edgecolor='black')
    ax3.axvline(x=1933, color='red', linestyle='--', label='Ti6Al4V melting point')
    ax3.set_xlabel('Temperature (K)')
    ax3.set_ylabel('Number of cells')
    ax3.set_title('Temperature Distribution')
    ax3.legend()

    # Statistics
    T_max = np.max(temp)
    T_min = np.min(temp)
    T_avg = np.mean(temp)

    fig.suptitle(f'File: {os.path.basename(vtk_file)} | '
                 f'T_min={T_min:.1f}K, T_avg={T_avg:.1f}K, T_max={T_max:.1f}K',
                 fontsize=10)

    plt.tight_layout()

    if save_fig:
        png_file = vtk_file.replace('.vtk', '.png')
        plt.savefig(png_file, dpi=150, bbox_inches='tight')
        print(f"Saved figure: {png_file}")

    plt.show()

def create_animation(file_pattern, z_slice=0, output_file='laser_heating.mp4'):
    """
    Create an animation from a series of VTK files

    Args:
        file_pattern: Glob pattern for VTK files
        z_slice: Z-index for visualization
        output_file: Output video filename
    """
    # Get all files
    files = sorted(glob.glob(file_pattern))

    if not files:
        print(f"No files found matching pattern: {file_pattern}")
        return

    print(f"Found {len(files)} files")

    # Read first file to get dimensions
    temp0, dims, spacing, _ = read_vtk_structured_points(files[0])
    if temp0 is None:
        print("Error reading first file")
        return

    nx, ny, nz = dims
    dx, dy, dz = spacing

    # Setup figure
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Initialize plots
    im1 = ax1.imshow(temp0[z_slice, :, :],
                     extent=[0, nx*dx*1e6, 0, ny*dy*1e6],
                     origin='lower', cmap=create_custom_colormap(),
                     vmin=300, vmax=1000)
    ax1.set_xlabel('X (µm)')
    ax1.set_ylabel('Y (µm)')
    ax1.set_title('Surface Temperature')
    plt.colorbar(im1, ax=ax1, label='Temperature (K)')

    im2 = ax2.imshow(temp0[:, ny//2, :],
                     extent=[0, nx*dx*1e6, 0, nz*dz*1e6],
                     origin='lower', cmap=create_custom_colormap(),
                     vmin=300, vmax=1000, aspect='auto')
    ax2.set_xlabel('X (µm)')
    ax2.set_ylabel('Z (µm)')
    ax2.set_title('Cross Section')
    plt.colorbar(im2, ax=ax2, label='Temperature (K)')

    title = fig.suptitle('')

    def update(frame):
        """Update function for animation"""
        temp, _, _, laser = read_vtk_structured_points(files[frame])
        if temp is None:
            return [im1, im2, title]

        # Update images
        im1.set_array(temp[z_slice, :, :])
        im2.set_array(temp[:, ny//2, :])

        # Update title with statistics
        T_max = np.max(temp)
        T_avg = np.mean(temp)
        title.set_text(f'Frame {frame}/{len(files)} | '
                      f'T_avg={T_avg:.1f}K, T_max={T_max:.1f}K')

        return [im1, im2, title]

    # Create animation
    print("Creating animation...")
    anim = FuncAnimation(fig, update, frames=len(files),
                        interval=50, blit=True)

    # Save animation
    try:
        anim.save(output_file, writer='ffmpeg', fps=20, dpi=100)
        print(f"Animation saved: {output_file}")
    except:
        print("Error: ffmpeg not found. Install with: sudo apt-get install ffmpeg")
        print("Showing interactive animation instead...")
        plt.show()

def analyze_time_series(file_pattern):
    """
    Analyze temperature evolution over time

    Args:
        file_pattern: Glob pattern for VTK files
    """
    files = sorted(glob.glob(file_pattern))

    if not files:
        print(f"No files found matching pattern: {file_pattern}")
        return

    times = []
    T_max_list = []
    T_avg_list = []
    T_min_list = []
    melt_fraction_list = []

    T_melt = 1933  # Ti6Al4V melting temperature in K

    print("Analyzing time series...")
    for i, file in enumerate(files):
        temp, dims, _, _ = read_vtk_structured_points(file)
        if temp is None:
            continue

        # Extract time from filename (assumes format: base_XXXXXX.vtk)
        match = re.search(r'_(\d{6})\.vtk', file)
        if match:
            step = int(match.group(1))
            times.append(step)

        # Calculate statistics
        T_max_list.append(np.max(temp))
        T_avg_list.append(np.mean(temp))
        T_min_list.append(np.min(temp))

        # Calculate melt fraction
        melt_fraction = np.sum(temp > T_melt) / temp.size
        melt_fraction_list.append(melt_fraction)

        if i % 10 == 0:
            print(f"  Processed {i+1}/{len(files)} files")

    # Create plots
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))

    # Temperature evolution
    ax = axes[0, 0]
    ax.plot(times, T_max_list, 'r-', label='T_max', linewidth=2)
    ax.plot(times, T_avg_list, 'g-', label='T_avg', linewidth=2)
    ax.plot(times, T_min_list, 'b-', label='T_min', linewidth=2)
    ax.axhline(y=T_melt, color='k', linestyle='--', alpha=0.5, label='T_melt')
    ax.set_xlabel('Time Step')
    ax.set_ylabel('Temperature (K)')
    ax.set_title('Temperature Evolution')
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Temperature range
    ax = axes[0, 1]
    T_range = np.array(T_max_list) - np.array(T_min_list)
    ax.plot(times, T_range, 'purple', linewidth=2)
    ax.set_xlabel('Time Step')
    ax.set_ylabel('Temperature Range (K)')
    ax.set_title('Temperature Gradient')
    ax.grid(True, alpha=0.3)

    # Melt fraction
    ax = axes[1, 0]
    ax.plot(times, np.array(melt_fraction_list) * 100, 'orange', linewidth=2)
    ax.set_xlabel('Time Step')
    ax.set_ylabel('Melt Fraction (%)')
    ax.set_title('Melting Evolution')
    ax.grid(True, alpha=0.3)

    # Heating rate
    ax = axes[1, 1]
    if len(T_max_list) > 1:
        heating_rate = np.gradient(T_max_list)
        ax.plot(times, heating_rate, 'red', linewidth=1)
        ax.set_xlabel('Time Step')
        ax.set_ylabel('Heating Rate (K/step)')
        ax.set_title('Maximum Temperature Rate of Change')
        ax.grid(True, alpha=0.3)

    plt.suptitle('Laser Heating Simulation Analysis', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

def main():
    """Main function with command-line interface"""

    print("="*50)
    print("  LBM Laser Heating Visualization Tool")
    print("="*50)

    if len(sys.argv) < 2:
        print("\nUsage:")
        print("  python visualize_temperature.py single <file.vtk>")
        print("  python visualize_temperature.py animate <pattern>")
        print("  python visualize_temperature.py analyze <pattern>")
        print("\nExamples:")
        print("  python visualize_temperature.py single visualization_output/laser_heating_000100.vtk")
        print("  python visualize_temperature.py animate 'visualization_output/laser_heating_*.vtk'")
        print("  python visualize_temperature.py analyze 'visualization_output/laser_heating_*.vtk'")
        sys.exit(1)

    mode = sys.argv[1]

    if mode == 'single':
        if len(sys.argv) < 3:
            print("Error: Please provide a VTK file")
            sys.exit(1)
        plot_single_timestep(sys.argv[2], save_fig=True)

    elif mode == 'animate':
        if len(sys.argv) < 3:
            print("Error: Please provide a file pattern")
            sys.exit(1)
        output_file = sys.argv[3] if len(sys.argv) > 3 else 'laser_heating.mp4'
        create_animation(sys.argv[2], output_file=output_file)

    elif mode == 'analyze':
        if len(sys.argv) < 3:
            print("Error: Please provide a file pattern")
            sys.exit(1)
        analyze_time_series(sys.argv[2])

    else:
        print(f"Error: Unknown mode '{mode}'")
        print("Valid modes: single, animate, analyze")
        sys.exit(1)

if __name__ == '__main__':
    main()